version: '3.8'

services:
  rag-system:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - server/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/server/uploads
      - ./data:/app/server/data
    restart: unless-stopped
